######################################################################
# Automatically generated by qmake (3.0) Sun Aug 5 15:30:29 2018
######################################################################

TEMPLATE = app
TARGET = atomic
INCLUDEPATH += .
CONFIG += c++11

# Input
HEADERS += BeadFinder.h Blob.h
SOURCES += main.cpp BeadFinder.cpp Blob.cpp
