######################################################################
# Automatically generated by qmake (3.0) Wed Jul 26 23:30:26 2017
######################################################################

TEMPLATE = app
TARGET = sierpinski
INCLUDEPATH += .
CONFIG += c++11

# Input
HEADERS += *.h
SOURCES += *.cpp

QT += gui
QT += widgets
