######################################################################
# Automatically generated by qmake (3.0) Sun Jul 29 09:02:45 2018
######################################################################

TEMPLATE = app
TARGET = LFSR
INCLUDEPATH += .
CONFIG += c++11

# Input
HEADERS += lfsr.h
SOURCES += lfsr.cpp main.cpp
