######################################################################
# Automatically generated by qmake (3.0) Wed Aug 22 17:27:38 2018
######################################################################

TEMPLATE = app
TARGET = colinear
INCLUDEPATH += .
CONFIG += c++11

# Input
HEADERS += Point.h
SOURCES += main.cpp

QT += widgets
QT += gui
