######################################################################
# Automatically generated by qmake (3.0) Sat Aug 4 12:01:01 2018
######################################################################

TEMPLATE = app
TARGET = tsp
INCLUDEPATH += .
CONFIG += c++11

# Input
HEADERS += Point.h Tour.h
SOURCES += main.cpp Point.cpp Tour.cpp

QT += widgets
QT += gui

